import 'dart:io';

import 'package:changelog_bubbler/src/bubbler_shell.dart';
import 'package:changelog_bubbler/src/platform_wrapper.dart';
import 'package:get_it/get_it.dart';
import 'package:mocktail/mocktail.dart';
import 'package:process_run/process_run.dart' show ProcessRunProcessResultExt;

class MockProcessResult extends Mock implements ProcessResult {}

class _MockBubblerShell extends Mock implements BubblerShell {}

class _MockPlatformWrapper extends Mock implements PlatformWrapper {}

Future<void> registerMockGlobalDependencies() async {
  await GetIt.I.reset();

  _stubShell();
  _stubPlatformWrapper();
}

void _stubShell() {
  final mockShell = _MockBubblerShell();
  final mockResult = MockProcessResult();
  when(() => mockShell.run(
        any(),
        workingDir: any(named: 'workingDir'),
      )).thenAnswer((_) async => mockResult);
  GetIt.I.registerLazySingleton<BubblerShell>(() => mockShell);
}

void _stubPlatformWrapper() {
  final mockPlatformWrapper = _MockPlatformWrapper();
  when(() => mockPlatformWrapper.isWindows).thenReturn(false);
  when(() => mockPlatformWrapper.home).thenReturn('mock_home/.pub-cache');
  GetIt.I.registerLazySingleton<PlatformWrapper>(() => mockPlatformWrapper);
}

extension TestHelper on BubblerShell {
  Future<ProcessResult> stubbedRun(
    String script, {
    String? workingDir,
  }) =>
      run(
        script,
        workingDir: workingDir ?? any(named: 'workingDir'),
      );

  ProcessResult stubbedRunSync(
    String script, {
    String? workingDir,
  }) =>
      runSync(
        script,
        workingDir: workingDir ?? any(named: 'workingDir'),
      );
}

extension ProcessResultExt on ProcessResult {
  static ProcessResult mock({String? outText}) {
    final mockResult = MockProcessResult();
    when(() => mockResult.outText).thenReturn(outText ?? '');
    return mockResult;
  }
}

class MockData {
  /// > dart pub deps --no-dev --style compact
  static const mockPubDepsOutput = '''
Dart SDK 2.19.2
Flutter SDK 3.7.3
changelog_bubbler 0.1.0

dependencies:
- get_it 7.6.0 [async]

transitive dependencies:
- async 2.11.0
''';

  static const mockPubYamlContents = '''
name: changelog_bubbler
version: 1.0.0

dependencies:
  get_it: ^7.4.1

dev_dependencies:
  mocktail: ^0.3.0

executables:
  changelog_bubbler: changelog_bubbler
''';

  static const mockPubLockContents = '''
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  async:
    dependency: transitive
    description:
      name: async
      sha256: "947bfcf187f74dbc5e146c9eb9c0f10c9f8b30743e341481c1e2ed3ecc18c20c"
      url: "https://pub.dev"
    source: hosted
    version: "2.11.0"
  get_it:
    dependency: "direct main"
    description:
      name: get_it
      sha256: "529de303c739fca98cd7ece5fca500d8ff89649f1bb4b4e94fb20954abcd7468"
      url: "https://pub.dev"
    source: hosted
    version: "7.6.0"
  matcher:
    dependency: transitive
    description:
      name: matcher
      sha256: "6501fbd55da300384b768785b83e5ce66991266cec21af89ab9ae7f5ce1c4cbb"
      url: "https://pub.dev"
    source: hosted
    version: "0.12.15"
  mocktail:
    dependency: "direct dev"
    description:
      name: mocktail
      sha256: "80a996cd9a69284b3dc521ce185ffe9150cde69767c2d3a0720147d93c0cef53"
      url: "https://pub.dev"
    source: hosted
    version: "0.3.0"
sdks:
  dart: ">=2.19.0 <3.0.0"
''';
}
