name: Validate PR

env:
  dart_version: 2.19.2

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main

jobs:
  pr_validation:
    name: Validate PR
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dart install
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.dart_version }}

      - name: Pub Get
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Publish dry run
        run: dart pub publish --dry-run
