name: Publish

env:
  dart_version: 2.19.2

# This workflow is triggered by tag creation
# Tags are created on each merge to `main`
#   because we don't want to need to manually create tags which align
#   with the version in the pubspec.yaml etc.
# The whole publish process is automated on merge to main

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC for pub.dev publish
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Dart install
        uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.dart_version }}

      - name: Pub Get
        run: dart pub get

      - name: Run Tests
        run: |
          dart test --coverage=coverage
          dart run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --report-on=lib

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

      - name: Publish
        run: dart pub publish --force